# Generated by Django 5.1.7 on 2025-03-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JumpingGameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_multiplier', models.FloatField(default=2.0)),
                ('enemy_spawn_rate', models.IntegerField(default=800)),
            ],
        ),
    ]
