# Generated by Django 5.1.7 on 2025-03-17 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locID', models.AutoField(primary_key=True, serialize=False)),
                ('postcode', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(default='Exeter')),
                ('location_name', models.CharField(default='Location Name', max_length=100)),
                ('checked_in', models.BooleanField(default=False)),
                ('task1_id', models.CharField(blank=True, max_length=100, null=True)),
                ('task2_id', models.CharField(blank=True, max_length=100, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
            ],
        ),
    ]
