# Generated by Django 5.1.7 on 2025-03-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='postcode',
        ),
    ]
