# Generated by Django 5.1.6 on 2025-03-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="id",
        ),
        migrations.AlterField(
            model_name="location",
            name="postcode",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
