# Generated by Django 5.1.6 on 2025-03-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_remove_location_id_alter_location_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="address",
            field=models.TextField(default="Exeter"),
        ),
        migrations.AddField(
            model_name="location",
            name="location_name",
            field=models.CharField(default="Location Name", max_length=100),
        ),
    ]
