# Generated by Django 5.1.7 on 2025-03-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_userlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='checked_in',
        ),
    ]
