# Generated by Django 5.1.7 on 2025-03-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_rename_location_userlocation_locationid_and_more"),
        ("quizzes", "0004_userquizscore"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="task1_id",
        ),
        migrations.RemoveField(
            model_name="location",
            name="task2_id",
        ),
        migrations.AddField(
            model_name="location",
            name="task1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task1",
                to="quizzes.quiz",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="task2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task2",
                to="quizzes.quiz",
            ),
        ),
    ]
