# Generated by Django 5.1.6 on 2025-02-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200, unique=True)),
                ("choice1", models.CharField(max_length=200)),
                ("choice2", models.CharField(max_length=200)),
                ("choice3", models.CharField(max_length=200)),
                ("choice4", models.CharField(max_length=200)),
                ("correct_choice", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="TrueFalse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200, unique=True)),
                ("is_true", models.BooleanField(default=True)),
            ],
        ),
    ]
