# Generated by Django 5.1.6 on 2025-02-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('user', 'USER'), ('admin', 'ADMIN')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reward_pts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
