# Generated by Django 5.1.6 on 2025-03-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_location_address_location_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="task1_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="task2_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="task3_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
