# Generated by Django 5.1.6 on 2025-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_location_task1_id_location_task2_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="locID",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="location",
            name="postcode",
            field=models.CharField(max_length=10),
        ),
    ]
