# Generated by Django 5.1.7 on 2025-03-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_checked_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocation',
            old_name='location',
            new_name='locationID',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='user',
            new_name='userID',
        ),
    ]
