# Generated by Django 5.1.6 on 2025-03-08 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_location_locid_alter_location_postcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="task3_id",
        ),
    ]
