# Generated by Django 5.1.7 on 2025-03-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0005_rename_location_userlocation_locationid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='task1_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='task1_type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='task2_type',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='task2_type', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='task1_id',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='task2_id',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='task1_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='task2_complete',
            field=models.BooleanField(default=True),
        ),
    ]
