# Generated by Django 5.1.7 on 2025-03-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0006_location_task1_type_location_task2_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='task1_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='task1_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task1_type', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='location',
            name='task2_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='task2_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task2_type', to='contenttypes.contenttype'),
        ),
    ]
