# Generated by Django 5.1.6 on 2025-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_remove_location_task3_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="task1_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="task2_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
