# Generated by Django 5.1.6 on 2025-03-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0007_alter_location_task1_id_alter_location_task2_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="locked_by",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
