# Generated by Django 5.1.6 on 2025-03-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0008_location_locked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="postcode",
            field=models.CharField(max_length=20),
        ),
    ]
