# Generated by Django 5.1.6 on 2025-03-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0009_alter_location_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
