# Generated by Django 5.1.7 on 2025-03-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sokoban_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
