# Generated by Django 5.1.7 on 2025-03-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sokoban_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sokoban_level',
            name='number',
        ),
    ]
